on: 
 push:
  branches: 
    -main

   jobs:
   buidl:
   runs-on: ubuntu-latest

   steps:
   - name: checkout repo
   uses: actions/checkout@v3

   - name: Setup dotnet
   uses: actions/setup-dotnet@v3
   with:
   dotnet-version: '6.0'

   - name: Build project
   run: dotnet restore; dotnet publish -o site;

   - name: create zip package
   run: cd site; zip ../site.zip *;

   - name: Deploy to aws EB
     uses: einaregilsson/beanstalk-deploy@v21
     with: 
      aws_acces_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_key: {{ secrets.AWS_SECRET_ACCESS_KEY }}
      application_name: calculator api
      enviroment_name: Calculatorapi-env
      version_lable: ${{ github.run_id }}
      region: eu-noth-1
      deployment_package: site.zip

